import type { AuthenticatedIdentity, DocumentSignatureRecord } from "@/lib/types/documentSignature";

function isoDaysAgo(days: number): string {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() - days);
  return d.toISOString();
}

/** Demo native records across worlds — only when mock mode is enabled. */
export function buildMockNativeRecords(identity: AuthenticatedIdentity): DocumentSignatureRecord[] {
  const { uid, eid_mappings, display_name } = identity;
  const person = display_name || "Verified Subscriber";
  const ciright = eid_mappings.find((m) => m.world_id === "world-ciright-ie") ?? eid_mappings[0];
  const vendor = eid_mappings.find((m) => m.world_id === "world-ciright-vendor") ?? eid_mappings[1];
  const customer = eid_mappings.find((m) => m.world_id === "world-customer-portal") ?? eid_mappings[2];

  const records: DocumentSignatureRecord[] = [
    {
      record_id: `rec-${uid}-vendor-agreement`,
      document_id: `doc-vendor-agreement-${uid}`,
      world_id: vendor.world_id,
      world_name: vendor.world_name,
      uid,
      eid: vendor.eid,
      user_role_on_document: "signed_by_me",
      person_display_name_from_world: person,
      document_name: "Vendor Agreement",
      document_type: "contract",
      document_status: "active",
      signature_status: "signed",
      signed_date: isoDaysAgo(12),
      created_date: isoDaysAgo(20),
      purpose: "Vendor onboarding and procurement",
      created_by_uid: "keyra-uid-other-001",
      created_by_eid: "eid-procurement",
      signed_by_uid: uid,
      signed_by_eid: vendor.eid,
      lead_uid: uid,
      lead_eid: vendor.eid,
      support_uid: null,
      support_eid: null,
      management_uid: uid,
      management_eid: vendor.eid,
      associated_uid_list: [],
      s3_bucket: null,
      s3_object_key: null,
      s3_region: null,
      checksum_hash: null,
      audit_log_id: `audit-${uid}-vendor-agreement`,
      visibility_scope: "world",
      source_system: "keyra-sig",
      imported_flag: false,
      imported_by_uid: null,
      imported_date: null,
    },
    {
      record_id: `rec-${uid}-nda-created`,
      document_id: `doc-nda-${uid}`,
      world_id: ciright.world_id,
      world_name: ciright.world_name,
      uid,
      eid: ciright.eid,
      user_role_on_document: "created_by_me",
      person_display_name_from_world: person,
      document_name: "Mutual NDA",
      document_type: "nda",
      document_status: "active",
      signature_status: "partially_signed",
      signed_date: null,
      created_date: isoDaysAgo(5),
      purpose: "Partnership exploration",
      created_by_uid: uid,
      created_by_eid: ciright.eid,
      signed_by_uid: null,
      signed_by_eid: null,
      lead_uid: uid,
      lead_eid: ciright.eid,
      support_uid: null,
      support_eid: null,
      management_uid: null,
      management_eid: null,
      associated_uid_list: ["keyra-uid-partner-88"],
      s3_bucket: null,
      s3_object_key: null,
      s3_region: null,
      checksum_hash: null,
      audit_log_id: `audit-${uid}-nda`,
      visibility_scope: "world",
      source_system: "keyra-sig",
      imported_flag: false,
      imported_by_uid: null,
      imported_date: null,
    },
    {
      record_id: `rec-${uid}-customer-order`,
      document_id: `doc-customer-order-${uid}`,
      world_id: customer.world_id,
      world_name: customer.world_name,
      uid,
      eid: customer.eid,
      user_role_on_document: "signed_by_me",
      person_display_name_from_world: person,
      document_name: "Service Order Confirmation",
      document_type: "order",
      document_status: "completed",
      signature_status: "signed",
      signed_date: isoDaysAgo(45),
      created_date: isoDaysAgo(46),
      purpose: "Customer service activation",
      created_by_uid: "keyra-uid-system",
      created_by_eid: "eid-system",
      signed_by_uid: uid,
      signed_by_eid: customer.eid,
      lead_uid: null,
      lead_eid: null,
      support_uid: uid,
      support_eid: customer.eid,
      management_uid: null,
      management_eid: null,
      associated_uid_list: [],
      s3_bucket: null,
      s3_object_key: null,
      s3_region: null,
      checksum_hash: null,
      audit_log_id: `audit-${uid}-order`,
      visibility_scope: "world",
      source_system: "keyra-sig",
      imported_flag: false,
      imported_by_uid: null,
      imported_date: null,
    },
    {
      record_id: `rec-${uid}-policy-associated`,
      document_id: `doc-policy-${uid}`,
      world_id: ciright.world_id,
      world_name: ciright.world_name,
      uid,
      eid: ciright.eid,
      user_role_on_document: "associated",
      person_display_name_from_world: person,
      document_name: "Workplace Safety Policy Acknowledgement",
      document_type: "policy",
      document_status: "archived",
      signature_status: "signed",
      signed_date: isoDaysAgo(180),
      created_date: isoDaysAgo(190),
      purpose: "Annual compliance acknowledgement",
      created_by_uid: "keyra-uid-hr",
      created_by_eid: "eid-hr",
      signed_by_uid: uid,
      signed_by_eid: ciright.eid,
      lead_uid: "keyra-uid-hr",
      lead_eid: "eid-hr",
      support_uid: null,
      support_eid: null,
      management_uid: null,
      management_eid: null,
      associated_uid_list: [uid],
      s3_bucket: null,
      s3_object_key: null,
      s3_region: null,
      checksum_hash: null,
      audit_log_id: `audit-${uid}-policy`,
      visibility_scope: "world",
      source_system: "keyra-sig",
      imported_flag: false,
      imported_by_uid: null,
      imported_date: null,
    },
  ];

  return records;
}
